###########################################################################################
#                                                                                         #
#                                      PROLIB CONFIGURATION                               #
#                                         BY PROFEWGAMES                                  #
#                                                                                         #
###########################################################################################

# Will debugging be enabled?
debugging: false

# The lobby server the players will be sent to upon shutdown request or other
# networking request via Redis or other source.
fallback-server: lobby

# The name of this server. * Must not include any special characters or spaces
server-name: Unknown-Server

# This is the auto-updating feature of ProLib. This is handy for network use.
# Enable: Should the updater be enabled?
# Secure Jar: Should the updater check the jar before downloading it? This is
#    Handy for preventing malware installation
# URL: This is the URL the auto-updater will try to retrieve the information from.
auto-updater:
  enabled: false
  secure-jar: true
  url: https://yourdomain.com/prolib.jar

formatting:
  primary: 'DARK_PURPLE'
  secondary: 'LIGHT_PURPLE'
  elemental: 'YELLOW'
  error: 'RED'

# Enabling this will add support for GUI's or "custom gui's" to be and linked via
# a configuration file.
custom-gui: false