main: xyz.ufactions.prolib.ProLib
name: ProLib
version: 1.02
author: ProFewGames
description: Developer libraries for plugins.
api-version: 1.14
permissions:
  prolib.networking.notify:
    description: Permission to view network notifications
    default: op
  prolib.command.itembuilder:
    description: Item Builder Command
    default: op