mysql:
  enabled: false
  connections:
    local:
      url: localhost:3306/local
      username: root
      password: 'walrus'
      type: LOCAL
    network:
      url: localhost:3306/network
      username: root
      password: 'walrus'
      type: NETWORK
redis:
  enabled: false
  host: localhost
  port: 6379
  password: 'walrus'